name: Python Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    build:
        runs-on: alpine-latest

        steps:
            - uses: actions/checkout@4

            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
                
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install coverage coverage-badge codecov unittest-xml-reporting

            - name: Run tests
              run: |
                coverage run -m unittest discover -s tests
                coverage report -m
                coverage xml
            - name: Archive code coverage results
              uses: actions/upload-artifact@v4
              with:
                name: coverage
                path: coverage.xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                slug: Lucs1590/strava-to-trainingpeaks
                file: coverage.xml
                flags: unittests
                fail_ci_if_error: true